language: java

before_cache:
  - rm -rf $HOME/.m2/repository/**/*-SNAPSHOT

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper


jdk:
  - oraclejdk8

notifications:
  email: true